version: '3.1'

services:
    api:
        build: #https://docs.docker.com/compose/compose-file/#dockerfile
          context: Docker/python
          dockerfile: Dockerfile
        environment:
         - VIRTUAL_HOST="api.myfood.dev"
        volumes:
          - ./WebServer:/app
        command: python server.py
        restart: always
        network_mode: "bridge"

    api2:
        build: #https://docs.docker.com/compose/compose-file/#dockerfile
          context: Docker/python
          dockerfile: Dockerfile
        environment:
         - VIRTUAL_HOST="api.myfood.dev"
        volumes:
          - ./WebServer:/app
        command: python server.py
        restart: always
        network_mode: "bridge"

    web:
        build:
          context: Docker/npm/
          dockerfile: Dockerfile
        environment:
         - VIRTUAL_HOST="myfood.dev"
        volumes:
          - ./WebClient:/app
        environment:
          NODE_PORT: 3000
          NODE_MODE: dev
        depends_on:
         - api
        command: [npm, start]
        #restart: always
        network_mode: "bridge"

    haproxy:
       image: 'dockercloud/haproxy:latest'
       links:
         - api
         - api2
         - web
       depends_on:
         - api
         - api2
         - web
       ports:
         - '80:80'
       network_mode: "bridge"
