version: '3.1'

services:
    api:
        build: #https://docs.docker.com/compose/compose-file/#dockerfile
          context: Docker/python
          dockerfile: Dockerfile-dev
        ports:
          - "1026:80"
        volumes:
          - ./WebServer:/app
        command: python server.py
    web:
        build:
          context: Docker/npm/
          dockerfile: Dockerfile-dev
        ports:
          - 8080:3000
        volumes:
          - ./WebClient:/app
        environment:
          NODE_PORT: 3000
          NODE_MODE: prod
        depends_on:
         - api
        command: [npm, start]
